name: Test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  npm:
    strategy:
      matrix:
        node: [12.x, 15.x]
        os: [ubuntu-latest]
        vue: [2, 3]
        
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}
      - run: npm -v
      - run: node .github/test.js "npm i" ${{ matrix.vue }} "latest"
  
  yarn:
    strategy:
      matrix:
        node: [12.x, 14.x]
        os: [ubuntu-latest]
        vue: [2, 3]
        yarn: [latest, berry]
        
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}
      - run: yarn set version ${{ matrix.yarn }}
      - run: yarn --version
      - run: node .github/test.js "yarn add" ${{ matrix.vue }} "latest"
  
  pnpm:
    strategy:
      matrix:
        node: [12.x, 14.x]
        os: [ubuntu-latest]
        vue: [2, 3]
        
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}
      - run: npm i -g pnpm
      - run: pnpm -v
      - run: node .github/test.js "pnpm i" ${{ matrix.vue }} "latest"
